window.BLOG_POSTS = [
  {
    slug: "how-to-scope-a-saas-mvp",
    title: "How to scope a SaaS MVP that actually ships",
    excerpt: "Practical steps to define scope, avoid creep, and get from idea to launch in weeks, not months.",
    date: "2025-01-15",
    author: "Standen",
    readTime: "12 min read",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=500&fit=crop",
    body: "<p>Scoping an MVP is one of the hardest parts of building a product. Most delays are not engineering problems. They are scope problems dressed up as engineering. This guide walks through how Standen scopes SaaS MVPs so founders ship in weeks with fixed budget and full code ownership.</p><h2>Start with one outcome, not a feature list</h2><p>Write the outcome in one sentence: <em>After using the product, the user can ___.</em> If you need the word \"and\" more than once, you are already carrying two products. Pick the outcome that proves the idea to the next ten buyers.</p><p>Examples of sharp outcomes:</p><ul><li>Podcast host publishes one episode end-to-end without leaving the app.</li><li>Ops lead sees live margin per client account without opening five tabs.</li><li>Customer approves a deliverable in one link without email back-and-forth.</li></ul><h2>Fix time and budget, then scope</h2><p>We work to fixed timelines, often 14 to 30 days depending on surface area. Once time and budget are set, we fit scope to that box. Features that do not serve the core outcome move to a roadmap column, not into version one.</p><p>This inversion feels uncomfortable if you are used to estimating after a wishlist. It is the main reason projects ship instead of drifting.</p><h2>Map the workflow before the wireframes</h2><p>List steps as a numbered flow: trigger, inputs, decisions, outputs, who gets notified. Circle the step that breaks today. That step is usually the spine of the MVP.</p><p>Only then sketch screens. UI that does not map to a workflow step is decoration.</p><h2>Define acceptance criteria you can test</h2><p>Each must-have story needs a pass/fail check. \"Nice dashboard\" is not acceptance criteria. \"User with role Admin can filter projects by status and export CSV\" is.</p><h2>Integrations: must-have vs later</h2><p>Stripe, email and one CRM integration cover most B2B MVPs. Everything else is a candidate for manual process or CSV until you have paying users. See our <a href=\"/guides/integrations-101.html\">integrations guide</a> for a priority framework.</p><h2>What we cut from almost every first build</h2><ul><li>Admin superpowers nobody has asked for yet.</li><li>Multiple pricing tiers before one plan converts.</li><li>Mobile apps before web workflow is proven.</li><li>AI features that are not the core differentiator.</li></ul><h2>Handover is part of scope</h2><p>Ownership means repo access, deployment runbook and documented env vars. If you cannot deploy a hotfix without the agency, you rented software. Scope handover explicitly in the statement of work.</p><p>Ready to turn your idea into a scoped, shippable MVP? <a href=\"https://calendly.com/standen/discovery-call\" target=\"_blank\" rel=\"noopener\">Book a discovery call</a> or read <a href=\"/guides/scope-first-build.html\">how to scope a first SaaS system in 14 days</a>.</p>"
  },
  {
    slug: "web-development-hampshire-what-to-expect",
    title: "What to expect from a fixed-scope product studio",
    excerpt: "Timelines, communication, and how Standen delivers scoped SaaS and custom software builds for founders.",
    date: "2025-01-08",
    author: "Standen",
    readTime: "10 min read",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop",
    body: "<p>Founders evaluating a product studio want predictability: what happens week by week, what you need to provide, and what you keep at the end. This article explains how Standen runs fixed-scope SaaS and custom software engagements.</p><h2>Before build: discovery and written scope</h2><p>Every project starts with a structured call: users, workflow, data sources, integrations, risks and success metric. You receive a written scope with deliverables, exclusions and acceptance criteria. Price and timeline are fixed from that document.</p><p>No build starts until scope is signed. That protects both sides from \"just one more thing\" mid-sprint.</p><h2>During build: private live link from early week one</h2><p>You see progress on a staging URL, not slide decks. Demos are short and frequent. Feedback goes into a visible log so scope changes are conscious trades, not silent drift.</p><h2>What we need from you</h2><ul><li>A single decision-maker for scope questions.</li><li>Access to tools (DNS, Stripe, email domain, API keys).</li><li>Sample data or anonymised exports where relevant.</li><li>Timely review of staging, usually within one business day.</li></ul><h2>Commercial terms</h2><p>SaaS and custom software builds start from <strong>£5,000</strong>; larger Enterprise scopes from <strong>£18,000</strong>. Typical payment split is 50% to start, 50% on handover unless milestones are agreed for longer work.</p><h2>What you keep</h2><p>Full source code, deployment access, documentation and the logic of how the system runs. No licence lock-in. You can host on your accounts and hire any developer to maintain the stack.</p><h2>After handover</h2><p>We do not trap you in retainers. Optional support is available, but the system is designed so you are not dependent on us for every change.</p><p>Explore <a href=\"/work.html\">case studies</a> or <a href=\"https://calendly.com/standen/discovery-call\" target=\"_blank\" rel=\"noopener\">book a call</a> to scope your build.</p>"
  },
  {
    slug: "when-to-build-custom-software-vs-saas",
    title: "When to build custom software vs use existing SaaS",
    excerpt: "Deciding between bespoke build and off-the-shelf tools? We break down the trade-offs so you can choose with confidence.",
    date: "2024-12-18",
    author: "Standen",
    readTime: "11 min read",
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=500&fit=crop",
    body: "<p>Not every problem needs custom software. Some need a better process inside tools you already pay for. This guide helps founders decide when to buy, when to build, and when to combine both.</p><h2>Use off-the-shelf SaaS when</h2><ul><li>The workflow is industry-standard (email, accounting, generic CRM).</li><li>Mature products exist and your edge is not in that workflow.</li><li>Time to value matters more than perfect fit.</li><li>Your team is small and admin overhead must stay low.</li></ul><h2>Build custom software when</h2><ul><li>Your product <em>is</em> the software you sell.</li><li>Internal ops are your bottleneck and spreadsheets are failing.</li><li>Integrations between five tools cost more than one owned system.</li><li>Data model, permissions or compliance do not fit vendor shapes.</li><li>You need 100% code ownership for investors or acquirers.</li></ul><h2>The hybrid pattern</h2><p>Most companies use HubSpot or similar for marketing, Stripe for payments, and custom software for the core workflow. Draw a line: generic commodity vs competitive advantage. Build the second category.</p><h2>Score it in 20 minutes</h2><p>Use our <a href=\"/guides/build-vs-buy-scorecard.html\">build vs buy scorecard</a>: score fit, repetition, integration pain, ownership and glue work. Same sheet every time you evaluate a vendor.</p><h2>Cost framing</h2><p>SaaS seat fees scale with headcount. Custom software has upfront build cost but flat maintenance. When seat fees exceed build ROI inside 12 to 18 months, custom often wins for internal ops.</p><h2>Common mistakes</h2><ul><li>Building because a demo was exciting, not because the workflow repeats weekly.</li><li>Buying enterprise SaaS that requires a full-time admin.</li><li>Starting custom without acceptance criteria.</li></ul><p>Need an honest view on your situation? <a href=\"https://calendly.com/standen/discovery-call\" target=\"_blank\" rel=\"noopener\">Book a call</a> or read <a href=\"/compare/custom-build-vs-off-the-shelf.html\">custom build vs off-the-shelf</a>.</p>"
  },
  {
    slug: "rapid-delivery-without-cutting-corners",
    title: "Rapid delivery without cutting corners",
    excerpt: "How we ship MVPs and web apps in weeks while keeping quality high and tech debt low.",
    date: "2024-12-05",
    author: "Standen",
    readTime: "10 min read",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=500&fit=crop",
    body: "<p>Fast delivery and quality are not opposites. Speed fails when scope is fuzzy or the stack is experimental. Speed succeeds with tight scope, proven technology and visible progress.</p><h2>Stack choices that respect your timeline</h2><p>We use proven stacks: modern React frontends, Node or Python APIs, Postgres, managed hosting. The goal is maintainability for your team after handover, not resume-driven framework choices.</p><h2>Scope is the main quality lever</h2><p>The biggest risk to quality is scope creep. New ideas go to a backlog unless they are essential to the agreed outcome. That discipline protects auth, billing and data model from last-minute patches.</p><h2>What we refuse to rush</h2><ul><li>Authentication and authorisation checks.</li><li>Payment webhooks and idempotency.</li><li>Database migrations and backups.</li><li>Secrets management and HTTPS everywhere.</li></ul><h2>What we accept in v1</h2><p>See <a href=\"/guides/technical-debt-mvp.html\">technical debt on SaaS MVPs</a>: duplicated UI is fine; ambiguous data ownership is not.</p><h2>How you stay in control</h2><p>Short cycles, staging demos and written change log. You steer while the work is fresh, not after a month in the dark.</p><h2>Recent delivery examples</h2><p>Live SaaS in <strong>21 days</strong> (OhMyPod). Forex research platform in <strong>12 days</strong>. Lead magnet tool in <strong>9 days</strong>. Different domains, same scoping discipline.</p><p>If you want to move fast without the usual trade-offs, <a href=\"https://calendly.com/standen/discovery-call\" target=\"_blank\" rel=\"noopener\">book a call</a> or browse the <a href=\"/blog.html\">full guide library</a>.</p>"
  }
];
